### ISSUE TITLE
Where is the DX dataset ?

### ISSUE THREAD

**Issue by zylm** [HCPLab-SYSU/Medical_DS#1]
The paper said that code will be released together with DX dataset, but I haven't found DX dataset ?

**Comment by zhouqixian** [comment]
Hi, you may send the email to the first author Lin Xu to get the DX dataset. And I will update the Cloud link on github latter. Thanks!

**Comment by zylm** [comment]
Thanks!

**Comment by zylm** [comment]
I have another question. I am confused with the file of "action_mat.txt", how to compute it, and what's the order of horizontal and vertical axes?
